version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    open-pull-requests-limit: 10
    schedule:
      interval: "monthly"